### ISSUE TITLE
Class "SQLite3" not found

### ISSUE THREAD

**Issue by marcusmyers** [beyondcode/expose#254]
No matter what way I try to start an expose server I constantly get the following error.

```sh
PHP Fatal error:  Uncaught Error: Class "SQLite3" not found in phar:///usr/local/bin/expose/vendor/clue/reactphp-sqlite/src/functions.php:65
Stack trace:
#0 phar:///usr/local/bin/expose/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Clue\React\SQLite\{closure}()
#1 phar:///usr/local/bin/expose/vendor/clue/ndjson-react/src/Decoder.php(131): Evenement\EventEmitter->emit()
#2 phar:///usr/local/bin/expose/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Clue\React\NDJson\Decoder->handleData()
#3 phar:///usr/local/bin/expose/vendor/react/stream/src/ReadableResourceStream.php(146): Evenement\EventEmitter->emit()
#4 phar:///usr/local/bin/expose/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\ReadableResourceStream->handleData()
#5 phar:///usr/local/bin/expose/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#6 phar:///usr/local/bin/expose/vendor/clue/reactphp-sqlite/src/functions.php(216): React\EventLoop\StreamSelectLoop->run()
#7 phar:///usr/local/bin/expose/expose(25): Clue\React\SQLite\runWorker()
#8 /usr/local/bin/expose(14): require('...')
#9 {main}
  thrown in phar:///usr/local/bin/expose/vendor/clue/reactphp-sqlite/src/functions.php on line 65
```

I've also installed expose through composer and get the same error.

I'm running the expose server on Ubuntu 20.04 with php 8.0.

**Comment by mpociot** [comment]
Hi!

Expose requires the `sqlite3` extension to be installed

**Comment by marcusmyers** [comment]
I didn't even think about that 🤦. Sorry for creating the issue.
