### ISSUE TITLE
Deprecation notices and service is not running

### ISSUE THREAD

**Issue by ahoiroman** [beyondcode/expose#291]
Hello everybody,

Using PHP 8.1, I am getting a lot of deprecation notices:

```
expose                                                            

Deprecated: Return type of HumbugBox3122\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/.box/src/RequirementCollection.php on line 12

Deprecated: Return type of HumbugBox3122\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/.box/src/RequirementCollection.php on line 16

Deprecated: getopt(): Passing null to parameter #1 ($short_options) of type string is deprecated in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/expose on line 22

Deprecated: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/container/Container.php on line 1355

Deprecated: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/container/Container.php on line 1366

Deprecated: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/container/Container.php on line 1378

Deprecated: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/container/Container.php on line 1391

Deprecated: Return type of PhpOption\Some::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/phpoption/phpoption/src/PhpOption/Some.php on line 152

Deprecated: Return type of PhpOption\None::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/phpoption/phpoption/src/PhpOption/None.php on line 118

Deprecated: Return type of Illuminate\Config\Repository::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/config/Repository.php on line 141

Deprecated: Return type of Illuminate\Config\Repository::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/config/Repository.php on line 152

Deprecated: Return type of Illuminate\Config\Repository::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/config/Repository.php on line 164

Deprecated: Return type of Illuminate\Config\Repository::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/config/Repository.php on line 175

Deprecated: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Finder.php on line 608

Deprecated: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Finder.php on line 690

Deprecated: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php on line 42

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 85

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() should either be compatible with FilesystemIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 113

Deprecated: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::current() should either be compatible with FilesystemIterator::current(): SplFileInfo|FilesystemIterator|string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 61

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 55

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::hasChildren() should either be compatible with RecursiveIterator::hasChildren(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 74

Deprecated: Return type of Symfony\Component\Finder\Iterator\ExcludeDirectoryFilterIterator::getChildren() should either be compatible with RecursiveIterator::getChildren(): ?RecursiveIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php on line 79

Deprecated: Return type of Symfony\Component\Finder\Iterator\FilenameFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/FilenameFilterIterator.php on line 28

Deprecated: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/ahoi/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/PathFilterIterator.php on line 27
```

Well - what I think is interesting: All those notices are deprecation notices, but nevertheless the service does not start up.

**Comment by korey-enright** [comment]
Same problem, though I get fatal errors. Looks like they've got `phar-updater`, which has been abandoned and archived

```
Deprecated: Return type of Symfony\Component\Finder\Iterator\PathFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/symfony/finder/Iterator/PathFilterIterator.php on line 27
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/Collection.php:1413
Stack trace:
#0 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/Collection.php(11): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', 'phar:///Users/k...', 1413)
#1 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/.box/vendor/composer/ClassLoader.php(444): include('phar:///Users/k...')
#2 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/.box/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///Users/k...')
#3 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/helpers.php(15): Composer\Autoload\ClassLoader->loadClass('Illuminate\\Supp...')
#4 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/PackageManifest.php(89): collect(Array)
#5 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config('aliases')
#6 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#7 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/framework/src/Bootstrap/RegisterFacades.php(71): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap(Object(LaravelZero\Framework\Application))
#8 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(236): LaravelZero\Framework\Bootstrap\RegisterFacades->bootstrap(Object(LaravelZero\Framework\Application))
#9 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith(Array)
#10 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/framework/src/Kernel.php(130): Illuminate\Foundation\Console\Kernel->bootstrap()
#11 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/framework/src/Kernel.php(102): LaravelZero\Framework\Kernel->bootstrap()
#12 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/framework/src/Kernel.php(89): LaravelZero\Framework\Kernel->ensureDefaultCommand(Object(Symfony\Component\Console\Input\ArgvInput))
#13 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/expose(46): LaravelZero\Framework\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose(14): require('phar:///Users/k...')
#15 {main} in phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/Collection.php on line 11
PHP Fatal error:  Uncaught Symfony\Component\ErrorHandler\Error\FatalError: During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/Collection.php:1413
Stack trace:
#0 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/Collection.php(11): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', 'phar:///Users/k...', 1413)
#1 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/.box/vendor/composer/ClassLoader.php(444): include('phar:///Users/k...')
#2 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/.box/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('phar:///Users/k...')
#3 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/helpers.php(15): Composer\Autoload\ClassLoader->loadClass('Illuminate\\Supp...')
#4 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/PackageManifest.php(89): collect(Array)
#5 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\Foundation\PackageManifest->config('aliases')
#6 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#7 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/framework/src/Bootstrap/RegisterFacades.php(71): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap(Object(LaravelZero\Framework\Application))
#8 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Application.php(236): LaravelZero\Framework\Bootstrap\RegisterFacades->bootstrap(Object(LaravelZero\Framework\Application))
#9 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\Foundation\Application->bootstrapWith(Array)
#10 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/framework/src/Kernel.php(130): Illuminate\Foundation\Console\Kernel->bootstrap()
#11 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/framework/src/Kernel.php(102): LaravelZero\Framework\Kernel->bootstrap()
#12 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/laravel-zero/framework/src/Kernel.php(89): LaravelZero\Framework\Kernel->ensureDefaultCommand(Object(Symfony\Component\Console\Input\ArgvInput))
#13 phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/expose(46): LaravelZero\Framework\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose(14): require('phar:///Users/k...')
#15 {main} in phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/Collection.php:11
Stack trace:
#0 {main}
  thrown in phar:///Users/koreyenright/.composer/vendor/beyondcode/expose/builds/expose/vendor/illuminate/collections/Collection.php on line 11
  ```

**Comment by paul-adams-985** [comment]
Same problem. Happened when I updated to PHP 8.1

**Comment by ahoiroman** [comment]
Is there a ETA for PHP 8.1 compatibility, @mpociot ?

**Comment by ahoiroman** [comment]
If you are running on PHP 8.1, you may want to install php8.0, too and, as @chrisdicarlo suggested in https://github.com/tighten/takeout/issues/260 , set an alias like this in `.zshrc`:

```
alias expose="/opt/homebrew/Cellar/php@8.0/8.0.13/bin/php ~/.composer/vendor/bin/expose"
```

**Comment by tanthammar** [comment]
Have the same issue.

**Comment by christianklemp** [comment]
I'm seeing this issue as well - thanks @ahoiroman for the workaround suggestion! Got it to work, just had to change the path to the Homebrew installed `php@8.0` 👍

**Comment by RVxLab** [comment]
Requiring `dev-master` worked for me until they make a release for PHP 8.1.

```shell
composer global require beyondcode/expose:dev-master
```
