### ISSUE TITLE
Release 2.1.0 failing to run with PHP 7.4

### ISSUE THREAD

**Issue by rodrigopedra** [beyondcode/expose#298]
I just updated expose today and when running a simple command it fails. I usually use it from a global composer installation.

I tried downloading the PHAR file as described [here](https://expose.dev/docs/getting-started/installation#php-archive-phar), and also got the same error.

For now I manually reverted to 2.0.2. I haven't tested it on other PHP versions.

Here are the error messages:

~~~bash
$ php -v
PHP 7.4.27 (cli) (built: Dec 20 2021 21:28:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies

$ curl https://github.com/beyondcode/expose/raw/master/builds/expose -L --output expose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    314      0 --:--:-- --:--:-- --:--:--   314
100 9742k  100 9742k    0     0  13.4M      0 --:--:-- --:--:-- --:--:-- 13.4M

$ chmod +x expose

$ ./expose share http://localhost:9090/ --subdomain=iron
Trying to use custom domain: iron
[2022-02-07 20:02:49] production.ERROR: syntax error, unexpected '|', expecting variable (T_VARIABLE) {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '|', expecting variable (T_VARIABLE) at phar:///home/rodrigo/code/project/expose/vendor/symfony/routing/RouteCollection.php:145)
[stacktrace]
#0 phar:///home/rodrigo/code/project/expose/.box/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile()
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#2 phar:///home/rodrigo/code/project/expose/app/Http/RouteGenerator.php(15): spl_autoload_call()
#3 phar:///home/rodrigo/code/project/expose/app/Client/Factory.php(46): App\\Http\\RouteGenerator->__construct()
#4 phar:///home/rodrigo/code/project/expose/app/Commands/ShareCommand.php(47): App\\Client\\Factory->__construct()
#5 phar:///home/rodrigo/code/project/expose/vendor/illuminate/container/BoundMethod.php(36): App\\Commands\\ShareCommand->handle()
#6 phar:///home/rodrigo/code/project/expose/vendor/illuminate/container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 phar:///home/rodrigo/code/project/expose/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#8 phar:///home/rodrigo/code/project/expose/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 phar:///home/rodrigo/code/project/expose/vendor/illuminate/container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#10 phar:///home/rodrigo/code/project/expose/vendor/illuminate/console/Command.php(136): Illuminate\\Container\\Container->call()
#11 phar:///home/rodrigo/code/project/expose/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#12 phar:///home/rodrigo/code/project/expose/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#13 phar:///home/rodrigo/code/project/expose/vendor/symfony/console/Application.php(1015): Illuminate\\Console\\Command->run()
#14 phar:///home/rodrigo/code/project/expose/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#15 phar:///home/rodrigo/code/project/expose/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#16 phar:///home/rodrigo/code/project/expose/vendor/illuminate/console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#17 phar:///home/rodrigo/code/project/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#18 phar:///home/rodrigo/code/project/expose/vendor/laravel-zero/framework/src/Kernel.php(91): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 phar:///home/rodrigo/code/project/expose/expose(46): LaravelZero\\Framework\\Kernel->handle()
#20 /home/rodrigo/code/project/expose(14): require('phar:///home/ro...')
#21 {main}
"}

[2022-02-07 20:02:49] production.ERROR: syntax error, unexpected 'static' (T_STATIC) {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'static' (T_STATIC) at phar:///home/rodrigo/code/project/expose/vendor/symfony/string/UnicodeString.php:44)
[stacktrace]
#0 phar:///home/rodrigo/code/project/expose/.box/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile()
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#2 phar:///home/rodrigo/code/project/expose/vendor/symfony/console/Helper/Helper.php(65): spl_autoload_call()
#3 phar:///home/rodrigo/code/project/expose/vendor/symfony/console/Application.php(860): Symfony\\Component\\Console\\Helper\\Helper::width()
#4 phar:///home/rodrigo/code/project/expose/vendor/symfony/console/Application.php(829): Symfony\\Component\\Console\\Application->doRenderThrowable()
#5 phar:///home/rodrigo/code/project/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Exceptions/Handler.php(681): Symfony\\Component\\Console\\Application->renderThrowable()
#6 phar:///home/rodrigo/code/project/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(378): Illuminate\\Foundation\\Exceptions\\Handler->renderForConsole()
#7 phar:///home/rodrigo/code/project/expose/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\\Foundation\\Console\\Kernel->renderException()
#8 phar:///home/rodrigo/code/project/expose/vendor/laravel-zero/framework/src/Kernel.php(91): Illuminate\\Foundation\\Console\\Kernel->handle()
#9 phar:///home/rodrigo/code/project/expose/expose(46): LaravelZero\\Framework\\Kernel->handle()
#10 /home/rodrigo/code/project/expose(14): require('phar:///home/ro...')
#11 {main}
"}

PHP Parse error:  syntax error, unexpected 'static' (T_STATIC) in phar:///home/rodrigo/code/project/expose/vendor/symfony/string/UnicodeString.php on line 44
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[2022-02-07 20:02:49] production.ERROR: Exception thrown without a stack frame {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Exception thrown without a stack frame at Unknown:0)
[stacktrace]
#0 {main}
"}

PHP Parse error:  syntax error, unexpected 'static' (T_STATIC) in phar:///home/rodrigo/code/project/expose/vendor/symfony/string/UnicodeString.php on line 44
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
~~~

EDIT: redacted project name

**Comment by mpociot** [comment]
Yup I just noticed that as well. The dependencies support both versions, but I can only provide one phar file. So I guess I need to remove the 2.1.0 tag and tag PHP 8.1 support as 3.0 🤔

**Comment by rodrigopedra** [comment]
Maybe, but even when installed from global composer it gives the same error.

I didn't dig a lot into the code, but I guess you are distributing the generated phar even when installing from global composer in the `./vendor/bin/expose` file?

I remember trying to change something in the code long ago and realizing execution is not reflected.

But in my opinion it is best to have a new major version, then adding a lot of if clauses to check for features. Or as this project has a commercial side and maybe you want to keep the broadest support possible, remove any new features related to PHP 8.1 and maintain the code according to the least common denominator between supported PHP versions.

**Comment by mpociot** [comment]
Thank you for your feedback.
The problem, in this case, does not come from newer features, but the fact that the older dependencies do not work on PHP 8.1, but they do work on 7.4.

So if you would build the PHAR yourself on 7.4 it would work, but the PHAR that we ship does not work on 7.4 anymore.

If we would stop shipping a PHAR file, this would mean that everyone who wants to use Expose would also need to install all of its dependencies (which most likely results in global dependency issues).

Therefore we decided to drop PHP 7.4 support in Expose 2.1.0. I just re-tagged the version.
Expose is still going to work with PHP 7.4, but as 7.4 is also no longer getting any active support, I think it's safe to remove it from future new feature releases.

**Comment by rodrigopedra** [comment]
I agree this is the best path.

Actually my personal projects are all in PHP 8+.

But this one project I am working for a contractor, and am using expose to test it, is required to be on 7.4 :(

But the project is close to the end, so I don't think I will have any problems until then. Thanks for your feedback and review

**Comment by adpeyre** [comment]
You dropped php7.4 but I think you have forgotten this change: https://github.com/beyondcode/expose/blob/master/Dockerfile#L1
